"""init19901

Revision ID: 03ea7d8308ce
Revises: 7ec9423d6613
Create Date: 2017-04-11 12:46:59.327914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ea7d8308ce'
down_revision = '7ec9423d6613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_date')
    # ### end Alembic commands ###
