"""init105

Revision ID: 0c9383aca826
Revises: e0ec2fd499a3
Create Date: 2017-04-07 15:21:32.111903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9383aca826'
down_revision = 'e0ec2fd499a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
