"""init1998300033

Revision ID: 1a09d08b2ade
Revises: f3e49a740c73
Create Date: 2017-05-01 23:13:59.745144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a09d08b2ade'
down_revision = 'f3e49a740c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rotates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('img_src', sa.String(length=200), nullable=True),
    sa.Column('article_src', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rotates')
    # ### end Alembic commands ###
