"""init101

Revision ID: 2596e344c005
Revises: 85df917f1d50
Create Date: 2017-04-06 17:29:17.268924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2596e344c005'
down_revision = '85df917f1d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
