"""init19983

Revision ID: 31af78ac43af
Revises: 368e4bb140a9
Create Date: 2017-05-01 22:47:47.682285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31af78ac43af'
down_revision = '368e4bb140a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rotates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('img_src', sa.String(length=100), nullable=True),
    sa.Column('article_src', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rotates')
    # ### end Alembic commands ###
