"""init9999

Revision ID: 368e4bb140a9
Revises: 8ea77248271b
Create Date: 2017-05-01 22:42:24.051102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '368e4bb140a9'
down_revision = '8ea77248271b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rotates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('img_src', sa.String(length=100), nullable=True),
    sa.Column('article_src', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Rotates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rotates',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('desc', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_src', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('article_src', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('rotates')
    # ### end Alembic commands ###
