"""init199830

Revision ID: 3e9aea65093f
Revises: 31af78ac43af
Create Date: 2017-05-01 22:49:01.096192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9aea65093f'
down_revision = '31af78ac43af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rotates', sa.Column('pub_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rotates', 'pub_date')
    # ### end Alembic commands ###
