"""init112

Revision ID: 44f59d42d681
Revises: f395f9a7a080
Create Date: 2017-04-08 14:26:01.540494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f59d42d681'
down_revision = 'f395f9a7a080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
