"""init19983000

Revision ID: 5f0e4d00d411
Revises: 9421ca9c430f
Create Date: 2017-05-01 23:12:39.596261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0e4d00d411'
down_revision = '9421ca9c430f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
