"""init19900

Revision ID: 7ec9423d6613
Revises: 482c9fee8c1c
Create Date: 2017-04-10 17:30:45.636245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec9423d6613'
down_revision = '482c9fee8c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
