"""init1010

Revision ID: 85df917f1d50
Revises: cd40bcf5e9b1
Create Date: 2017-04-06 17:21:22.013494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85df917f1d50'
down_revision = 'cd40bcf5e9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
