"""init106

Revision ID: 891ff283dab8
Revises: 0c9383aca826
Create Date: 2017-04-07 15:22:21.642295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891ff283dab8'
down_revision = '0c9383aca826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('pub_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'pub_date')
    # ### end Alembic commands ###
