"""init999

Revision ID: 8ea77248271b
Revises: 03ea7d8308ce
Create Date: 2017-05-01 22:40:22.407748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea77248271b'
down_revision = '03ea7d8308ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rotates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('img_src', sa.String(length=100), nullable=True),
    sa.Column('article_src', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Rotates')
    # ### end Alembic commands ###
