"""init1998300

Revision ID: 9421ca9c430f
Revises: 3e9aea65093f
Create Date: 2017-05-01 23:07:04.352154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9421ca9c430f'
down_revision = '3e9aea65093f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
