"""init108

Revision ID: b95ece7442e8
Revises: 891ff283dab8
Create Date: 2017-04-08 01:19:58.354347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95ece7442e8'
down_revision = '891ff283dab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('last_modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'last_modify_date')
    # ### end Alembic commands ###
