"""init3

Revision ID: ba4543192f73
Revises: a911d589068c
Create Date: 2017-04-01 18:28:51.366408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4543192f73'
down_revision = 'a911d589068c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptions', sa.Column('pub_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('descriptions', 'pub_date')
    # ### end Alembic commands ###
