"""init100

Revision ID: cd40bcf5e9b1
Revises: ba4543192f73
Create Date: 2017-04-06 17:15:56.282051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd40bcf5e9b1'
down_revision = 'ba4543192f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useridToRoleid', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useridToRoleid', 'id')
    # ### end Alembic commands ###
