"""init199

Revision ID: d3f0dfa4e25f
Revises: 2695dab07f88
Create Date: 2017-04-09 13:36:24.154100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f0dfa4e25f'
down_revision = '2695dab07f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('pub_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'pub_date')
    # ### end Alembic commands ###
