"""init

Revision ID: ec4cb4771627
Revises: 
Create Date: 2017-04-01 17:37:59.950564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4cb4771627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('basename', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('articleid', sa.Integer(), nullable=True),
    sa.Column('col_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('callback_url', sa.String(length=50), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roleidToIdentityid',
    sa.Column('roleid', sa.Integer(), nullable=True),
    sa.Column('identityid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['identityid'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['roleid'], ['roles.id'], )
    )
    op.create_table('useridToRoleid',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('roleid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roleid'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], )
    )
    op.create_table('articleidToTagid',
    sa.Column('articleid', sa.Integer(), nullable=True),
    sa.Column('tagid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articleid'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tagid'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articleidToTagid')
    op.drop_table('useridToRoleid')
    op.drop_table('roleidToIdentityid')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('roles')
    op.drop_table('links')
    op.drop_table('identities')
    op.drop_table('collections')
    op.drop_table('categories')
    # ### end Alembic commands ###
