"""init111

Revision ID: f395f9a7a080
Revises: 9b0bb615dad8
Create Date: 2017-04-08 14:16:57.107316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f395f9a7a080'
down_revision = '9b0bb615dad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
